# Generated by Django 5.2.7 on 2025-10-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ("username",),
                "verbose_name": "cook",
                "verbose_name_plural": "cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("name",), "verbose_name_plural": "dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="cook",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
